#!/usr/bin/env python3
"""
enrich_shortlist_pricing.py — Phase 2b of the hardware procurement pipeline.

Takes a shortlist CSV generated by build_shortlist.py and outputs an enriched
version with empty columns for live pricing intelligence (cashback, student discounts,
stackable coupons, etc.).

Usage:
    python scripts/enrich_shortlist_pricing.py NotebookLM_Workspaces/intake/shortlist/YYYY-MM-DD_shortlist.csv
"""

import argparse
import csv
import sys
from pathlib import Path

PRICING_COLUMNS = [
    "current_best_price_aud",
    "current_best_retailer",
    "current_best_url",
    "in_stock_now",
    "student_discount_possible",
    "cashback_possible",
    "cashback_source",
    "stackable_coupons_confirmed",
    "price_match_possible",
    "price_beat_possible",
    "effective_best_price_aud",
    "promo_notes",
    "pricing_checked_at"
]

def main():
    parser = argparse.ArgumentParser(description="Add pricing enrichment columns to a shortlist CSV.")
    parser.add_argument("csv_path", type=str, help="Path to the input shortlist CSV")
    args = parser.parse_args()

    input_path = Path(args.csv_path)
    if not input_path.exists():
        sys.exit(f"Error: Input file {input_path} does not exist.")

    output_path = input_path.parent / f"{input_path.stem}_pricing_enriched.csv"

    with open(input_path, "r", encoding="utf-8") as fin:
        reader = csv.DictReader(fin)
        fieldnames = reader.fieldnames
        if not fieldnames:
            sys.exit("Error: Input CSV has no headers.")
            
        # Avoid duplicating columns if ran twice
        new_fieldnames = list(fieldnames)
        for col in PRICING_COLUMNS:
            if col not in new_fieldnames:
                new_fieldnames.append(col)

        rows = list(reader)

    # Initialize new columns to blank
    for row in rows:
        for col in PRICING_COLUMNS:
            if col not in row:
                row[col] = ""

    with open(output_path, "w", newline="", encoding="utf-8") as fout:
        writer = csv.DictWriter(fout, fieldnames=new_fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"\n✅ Pricing enrichment scaffold created successfully!")
    print(f"   Output: {output_path}")
    print(f"\n   Next Steps:")
    print(f"   1. Use the prompt template in `scripts/prompt_templates/browser_pricing_lookup.md`")
    print(f"      to instruct your Vercel Browser Agent to look up live prices.")
    print(f"   2. Fill in the new pricing columns in the enriched CSV.")
    print(f"   3. Score the candidates and run `rubric_weighting_engine.py --profile merged`")

if __name__ == "__main__":
    main()
